import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { FormEvent, useEffect, useState } from "react";
import CanvasBoard from "../components/CanvasBoard";
import Link from "next/link";
import Layout from "../components/Layout";

export default function Home() {
  const [body, setBody] = useState("");

  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>たてかんメーカー</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="text-center">
          <main className={styles.main}>
            <h1 className={styles.title}>
              ようこそ<a>たてかんメーカーへ！</a>
            </h1>
            <div className="row justify-content-center mb-3">
              {/* <div className="col-12 col-md-6"> */}
              <textarea
                className="form-control"
                placeholder="文字をいれてね！"
                rows={6}
                value={body}
                onChange={(e) => setBody(e.target.value)}
                required
              ></textarea>
              <div>
                <CanvasBoard text={body}></CanvasBoard>
              </div>
              {/* </div> */}
            </div>

            <Link href={`/${body}`}>
              <a className="tatekan-button">たてかんを作成する</a>
            </Link>
          </main>
        </div>

        {/* <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer> */}
      </div>
    </Layout>
  );
}
