import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { FormEvent, useEffect, useState } from "react";
import TwitterShareButton from "../components/TwitterShareButton";

export default function Home() {
  const [body, setBody] = useState("h");
  const ogpImageUrl = `${process.env.NEXT_PUBLIC_WEB_URL}/api/ogp?id=${body}/ogp`;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta property="og:image" key="ogImage" content={ogpImageUrl} />
        <meta
          name="twitter:card"
          key="twitterCard"
          content="summary_large_image"
        />
        <meta name="twitter:image" key="twitterImage" content={ogpImageUrl} />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          ようこそ<a>たてかんメーカーへ！</a>
        </h1>

        <textarea
          className="form-control"
          placeholder="おげんきですか？"
          rows={6}
          value={body}
          onChange={(e) => setBody(e.target.value)}
          required
        ></textarea>
        <TwitterShareButton
          url={`${process.env.NEXT_PUBLIC_WEB_URL}/`}
          text={body}
        ></TwitterShareButton>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
